const projects = [
  {
    name: "Epic Battle Quest",
    buttonText: "Скачать",
    description: "Скачай и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "epic_battle_quest",
  },
  {
    name: "Mystic Puzzle Saga",
    buttonText: "Зарегистрироваться",
    description: "Зарегистрируйся и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "mystic_puzzle_saga",
  },
  {
    name: "Galaxy Racer X",
    buttonText: "Скачать",
    description: "Скачай и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "galaxy_racer_x",
  },
  {
    name: "Fantasy Kingdom",
    buttonText: "Зарегистрироваться",
    description: "Зарегистрируйся и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "fantasy_kingdom",
  },
  {
    name: "Adventure Runner",
    buttonText: "Скачать",
    description: "Скачай и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "adventure_runner",
  },
  {
    name: "Zombie Survival 3D",
    buttonText: "Зарегистрироваться",
    description: "Зарегистрируйся и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "zombie_survival_3d",
  },
  {
    name: "Space Miner",
    buttonText: "Скачать",
    description: "Скачай и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "space_miner",
  },
  {
    name: "Treasure Hunt",
    buttonText: "Зарегистрироваться",
    description: "Зарегистрируйся и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "treasure_hunt",
  },
  {
    name: "Warrior's Journey",
    buttonText: "Скачать",
    description: "Скачай и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "warriors_journey",
  },
  {
    name: "Magic Duel",
    buttonText: "Зарегистрироваться",
    description: "Зарегистрируйся и получи +1 прокрут",
    link: "https://www.google.ru/?hl=ru",
    shortName: "magic_duel",
  },
];
module.exports = projects;